# Generated by Django 2.1 on 2018-11-29 20:03

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewed_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewed_product',
            name='products',
        ),
        migrations.AddField(
            model_name='viewed_product',
            name='products',
            field=models.SlugField(blank=True, unique=True, verbose_name=products.models.Product),
        ),
    ]
