# Generated by Django 2.1 on 2018-11-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewed_products', '0002_auto_20181129_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed_product',
            name='products',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
