# Generated by Django 2.1 on 2018-11-29 20:06

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewed_products', '0003_auto_20181129_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed_product',
            name='products',
            field=models.SlugField(blank=True, verbose_name=products.models.Product),
        ),
    ]
