# Generated by Django 2.1 on 2018-11-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewed_products', '0005_auto_20181129_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed_product',
            name='products',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
