# Generated by Django 2.1 on 2018-11-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_timestamp'),
        ('viewed_products', '0006_auto_20181129_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewed_product',
            name='products',
        ),
        migrations.AddField(
            model_name='viewed_product',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
