# Generated by Django 2.1 on 2018-12-04 15:34

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewed_products', '0007_auto_20181129_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewed_product',
            name='products',
        ),
        migrations.AddField(
            model_name='viewed_product',
            name='products',
            field=models.SlugField(blank=True, verbose_name=products.models.Product),
        ),
    ]
