# Generated by Django 2.1 on 2018-12-07 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewed_products', '0008_auto_20181204_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewed_Product_Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='viewed_product',
            name='products',
        ),
        migrations.AddField(
            model_name='viewed_product_objects',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewed_products.Viewed_Product'),
        ),
    ]
