# Generated by Django 2.1 on 2018-12-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewed_products', '0009_auto_20181206_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewed_Product_Objects',
            new_name='Viewed_Product_Object',
        ),
    ]
