# Generated by Django 2.1 on 2018-12-13 17:31

from django.db import migrations, models
import django.utils.timezone
import viewed_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewed_products', '0010_auto_20181206_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewed_product_object',
            name='products',
        ),
        migrations.AddField(
            model_name='viewed_product_object',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viewed_product_object',
            name='description',
            field=models.TextField(default=models.SlugField(blank=True, unique=True)),
        ),
        migrations.AddField(
            model_name='viewed_product_object',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewed_product_object',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=viewed_products.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='viewed_product_object',
            name='price',
            field=models.DecimalField(decimal_places=2, default=39.99, max_digits=20),
        ),
        migrations.AddField(
            model_name='viewed_product_object',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='viewed_product_object',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewed_product_object',
            name='title',
            field=models.CharField(default='first-title', max_length=120),
            preserve_default=False,
        ),
    ]
