# Generated by Django 2.1 on 2018-12-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewed_products', '0012_auto_20181213_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed_product_object',
            name='description',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='viewed_product_object',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
