# Generated by Django 2.1 on 2018-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewed_products', '0014_auto_20181213_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewed_product_object',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
