# Generated by Django 2.1 on 2018-12-14 17:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewed_products', '0015_auto_20181213_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Viewed_Product',
            new_name='Viewed_Product_User',
        ),
    ]
